// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/


module.exports = {
  src_folders : ['tests'],
  globals_path: 'tests/src/globals/globals.js',
  page_objects_path: 'tests/src/pages',

  webdriver : {
    start_process: true,
        server_path: 'node_modules/.bin/chromedriver',
        port: 4444
  },

  test_settings : {
    default : {
      desiredCapabilities: {
        browserName: 'chrome'
      }
    }
  }
}
